pipeline {
    agent any
    stages {
        stage('Build-Salam-Test') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver-Alhamdulillah') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
        stage('Complete-MashaAllah') {
            steps {
                echo 'Job Complete It works!'
            }
        }
    }
}
